###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: 'mariadb:10.10'
      command: --max_allowed_packet=104857600      # Set max_allowed_packet to 256M (or any other value)
      container_name: hotcrp-database
      restart: always
      volumes:
        - .:/application
      working_dir: /application
      environment:
          - MYSQL_ROOT_PASSWORD=rootpwd
          - MYSQL_DATABASE=hotcrp
          - MYSQL_USER=hotcrp
          - MYSQL_PASSWORD=hotcrppwd
      ports:
          - "9002:3306"

    webserver:
      image: nginx:alpine
      container_name: hotcrp-web
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php-fpm
      links:
        - php-fpm
      ports:
       - "9000:80"
       - "9443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: hotcrp-php
      working_dir: /application
      links:
        - mariadb
      ports:
        - "9001:9000"
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: hotcrp-database-admin
      working_dir: /application
      links:
        - mariadb
      environment:
        - PMA_HOST=hotcrp-database
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=rootpwd
      ports:
        - "9005:80"
